const $=id=>document.getElementById(id),BLUE='#0B5ED7';
const templates={general:{route:'VẬN CHUYỂN QUỐC TẾ',headline:'GIAO HÀNG NHANH - AN TOÀN - TẬN NƠI',cta:'LIÊN HỆ NGAY ĐỂ NHẬN BÁO GIÁ'},us:{route:'VIỆT NAM → MỸ',headline:'NHẬN GỬI HÀNG ĐI MỸ',cta:'LIÊN HỆ NGAY ĐỂ NHẬN BÁO GIÁ ĐI MỸ'},uk:{route:'VIỆT NAM → ANH',headline:'NHẬN GỬI HÀNG ĐI ANH',cta:'LIÊN HỆ NGAY ĐỂ NHẬN BÁO GIÁ ĐI ANH'},au:{route:'VIỆT NAM → ÚC',headline:'NHẬN GỬI HÀNG ĐI ÚC',cta:'LIÊN HỆ NGAY ĐỂ NHẬN BÁO GIÁ ĐI ÚC'},ca:{route:'VIỆT NAM → CANADA',headline:'NHẬN GỬI HÀNG ĐI CANADA',cta:'LIÊN HỆ NGAY ĐỂ NHẬN BÁO GIÁ ĐI CANADA'}};
const homelandSongs=[
['✈️ Xa xứ & trở về','Gửi Những Người Con Phương Xa','', 'người Việt nơi đất khách, sân bay, gói quà quê, mâm cơm gia đình'],
['✈️ Xa xứ & trở về','Đi Về Nhà','Đen x JustaTee','sân bay, vali, bố mẹ và bữa cơm đoàn tụ'],
['✈️ Xa xứ & trở về','Đi Để Trở Về','SOOBIN','thành phố nước ngoài, chuyến bay trở về'],
['🏡 Quê nhà','Quê Hương','Giáp Văn Thạch','con đường làng, cánh đồng, hàng tre, mái nhà cũ'],
['🏡 Quê nhà','Khúc Hát Sông Quê','Nguyễn Trọng Tạo','bến sông, phù sa, con đò, mùa gặt'],
['🏡 Quê nhà','Về Quê','Phó Đức Phương','đường về làng, người thân đón cửa'],
['👨‍👩‍👧 Gia đình & cha mẹ','Mang Tiền Về Cho Mẹ','Đen','mẹ nấu cơm, gian bếp, món quà gửi về'],
['👨‍👩‍👧 Gia đình & cha mẹ','Nhật Ký Của Mẹ','Hiền Thục','ảnh gia đình, mẹ tiễn con đi xa'],
['🍲 Bữa cơm & món quen','Còn Thương Rau Đắng Mọc Sau Hè','Bắc Sơn','rau vườn, cá kho, canh chua, mâm cơm quê'],
['🧒 Tuổi thơ & ký ức','Có Chàng Trai Viết Lên Cây','Phan Mạnh Quỳnh','sân trường, cây cũ, con đường tuổi thơ'],
['🗺 Miền Trung & vùng miền','Một Khúc Tâm Tình Của Người Hà Tĩnh','Nguyễn Văn Tý','núi Hồng Lĩnh, sông La, biển Hà Tĩnh'],
['🏙 Phố xưa & nơi để nhớ','Nhớ Về Hà Nội','Hoàng Hiệp','Hồ Gươm, phố cũ, hàng cây mùa thu'],
['🏙 Phố xưa & nơi để nhớ','Sài Gòn Đẹp Lắm','Y Vân','chợ Bến Thành, cà phê vỉa hè, đường phố'],
['🌊 Sông biển & làng quê','Biển Nhớ','Trịnh Công Sơn','biển chiều, bờ cát, người đứng nhớ quê']];
let mediaItems=[],logoBitmap=null,musicFile=null,running=false,urls=[];
const obj=f=>{const u=URL.createObjectURL(f);urls.push(u);return u};window.addEventListener('beforeunload',()=>urls.forEach(URL.revokeObjectURL));
function save(){const d={};['brandName','phone','address','template','ratio','quality','photoDuration','musicVolume'].forEach(k=>d[k]=$(k).value);localStorage.setItem('sve-pwa',JSON.stringify(d))}
function load(){try{const d=JSON.parse(localStorage.getItem('sve-pwa')||'{}');Object.entries(d).forEach(([k,v])=>$(k)&&($(k).value=v))}catch{}}
['brandName','phone','address','template','ratio','quality','photoDuration','musicVolume'].forEach(k=>$(k).addEventListener('change',()=>{save();drawPlaceholder()}));
$('musicVolume').oninput=e=>$('volumeValue').textContent=e.target.value+'%';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
$('installHelpBtn').onclick=()=>$('installDialog').showModal();$('closeInstall').onclick=()=>$('installDialog').close();
$('logoInput').onchange=async e=>{const f=e.target.files[0];$('logoName').textContent=f?f.name:'Chưa chọn logo';if(f){try{logoBitmap=await createImageBitmap(f)}catch{logoBitmap=null}}drawPlaceholder()};
$('mediaInput').onchange=e=>{for(const f of e.target.files)mediaItems.push({file:f,type:f.type.startsWith('video/')?'video':'image',url:obj(f)});renderMedia();e.target.value=''};
function renderMedia(){const box=$('mediaList');box.innerHTML='';box.classList.toggle('empty',!mediaItems.length);if(!mediaItems.length){box.textContent='Chưa có ảnh/video';drawPlaceholder();return}mediaItems.forEach((m,i)=>{const d=document.createElement('div');d.className='media-item';const v=document.createElement(m.type==='video'?'video':'img');v.src=m.url;if(m.type==='video'){v.muted=true;v.playsInline=true}const badge=document.createElement('span');badge.className='media-badge';badge.textContent=m.type==='video'?'VIDEO':'ẢNH';const del=document.createElement('button');del.textContent='×';del.onclick=()=>{mediaItems.splice(i,1);renderMedia()};d.append(v,badge,del);box.append(d)});drawPlaceholder()}
$('musicInput').onchange=e=>{musicFile=e.target.files[0]||null;$('musicName').textContent=musicFile?musicFile.name:'Chưa chọn nhạc';if(musicFile)$('musicPreview').src=obj(musicFile)};
const cats=['Tất cả',...new Set(homelandSongs.map(x=>x[0]))];$('homelandCategory').innerHTML=cats.map(c=>`<option>${c}</option>`).join('');$('homelandCategory').onchange=renderSuggestions;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderSuggestions(){const cat=$('homelandCategory').value,q=$('musicSearch').value.toLowerCase();const arr=homelandSongs.filter(s=>(cat==='Tất cả'||s[0]===cat)&&(!q||(`${s[1]} ${s[2]}`.toLowerCase().includes(q))));$('songSuggestions').innerHTML=arr.map(s=>`<div class="song"><div class="song-title">${esc(s[1])}${s[2]?' — '+esc(s[2]):''}</div><div class="song-meta">${esc(s[0])} • Cảnh: ${esc(s[3])}</div><div class="song-actions"><button data-p="${encodeURIComponent(s[1]+' '+s[2])}">▶ Tìm preview</button><button data-s="${encodeURIComponent(s[1]+' '+s[2])}">Mở nguồn</button></div></div>`).join('')||'<div class="song">Không có bài phù hợp.</div>';document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>searchPreview(decodeURIComponent(b.dataset.p),true));document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>window.open('https://music.apple.com/vn/search?term='+b.dataset.s,'_blank'))}
$('musicSearchBtn').onclick=()=>{renderSuggestions();if($('musicSearch').value.trim())searchPreview($('musicSearch').value.trim(),false)};$('musicSearch').oninput=renderSuggestions;
async function searchPreview(term,play){setStatus('Đang tìm preview: '+term+'…');try{const r=await fetch('https://itunes.apple.com/search?media=music&entity=song&country=vn&limit=8&term='+encodeURIComponent(term)),d=await r.json(),h=d.results.find(x=>x.previewUrl);if(!h)throw Error('Không có preview');$('musicPreview').src=h.previewUrl;$('musicName').textContent=`Preview: ${h.trackName} — ${h.artistName}`;if(play)await $('musicPreview').play().catch(()=>{});setStatus('Đã tìm thấy preview.')}catch(e){setStatus('Không tìm được preview: '+e.message)}}
function size(){const q=+$('quality').value,r=$('ratio').value;if(r==='9:16')return q===1080?[1080,1920]:[720,1280];if(r==='1:1')return q===1080?[1080,1080]:[720,720];return q===1080?[1920,1080]:[1280,720]}
function cfg(){const [w,h]=size(),c=$('previewCanvas');c.width=w;c.height=h;return c}
function blue(ctx,text,x,y,fs,align='left',weight=700){ctx.font=`${weight} ${fs}px -apple-system,BlinkMacSystemFont,"Segoe UI",Arial`;ctx.textAlign=align;ctx.lineJoin='round';ctx.lineWidth=Math.max(2,fs*.07);ctx.strokeStyle='rgba(255,255,255,.96)';ctx.strokeText(text,x,y);ctx.fillStyle=BLUE;ctx.fillText(text,x,y)}
function overlay(ctx,c,t,cta=false){const p=c.width*.045;if(cta){ctx.fillStyle='rgba(10,24,40,.58)';ctx.fillRect(0,0,c.width,c.height);blue(ctx,t.headline,c.width/2,c.height*.28,c.width*.055,'center',800);blue(ctx,t.route,c.width/2,c.height*.4,c.width*.043,'center');blue(ctx,$('brandName').value,c.width/2,c.height*.55,c.width*.05,'center',800);blue(ctx,t.cta,c.width/2,c.height*.68,c.width*.038,'center',800);blue(ctx,'ĐIỆN THOẠI: '+$('phone').value,c.width/2,c.height*.78,c.width*.038,'center');blue(ctx,$('address').value,c.width/2,c.height*.86,c.width*.028,'center')}else{blue(ctx,t.route,p,p+c.width*.045,c.width*.036);blue(ctx,$('brandName').value,p,c.height-c.width*.15,c.width*.055);blue(ctx,'ĐIỆN THOẠI: '+$('phone').value,p,c.height-c.width*.09,c.width*.032);blue(ctx,$('address').value,p,c.height-c.width*.045,c.width*.027)}if(logoBitmap){const mw=c.width*.2,mh=c.height*.12,sc=Math.min(mw/logoBitmap.width,mh/logoBitmap.height,1),w=logoBitmap.width*sc,h=logoBitmap.height*sc;ctx.drawImage(logoBitmap,c.width-w-p,p,w,h)}}
function drawPlaceholder(){const c=cfg(),x=c.getContext('2d'),t=templates[$('template').value];x.fillStyle='#142334';x.fillRect(0,0,c.width,c.height);overlay(x,c,t,false);x.fillStyle='rgba(255,255,255,.8)';x.textAlign='center';x.font=`${Math.round(c.width*.026)}px system-ui`;x.fillText(mediaItems.length?`${mediaItems.length} cảnh đã chọn`:'Thêm ảnh/video để bắt đầu',c.width/2,c.height*.5)}
function fit(ctx,src,w,h,z=1){const sw=src.videoWidth||src.width,sh=src.videoHeight||src.height;if(!sw||!sh)return;const sc=Math.max(w/sw,h/sh)*z,dw=sw*sc,dh=sh*sc;ctx.drawImage(src,(w-dw)/2,(h-dh)/2,dw,dh)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function source(m){if(m.type==='image'){const i=new Image();i.src=m.url;await i.decode();return i}const v=document.createElement('video');v.src=m.url;v.muted=true;v.playsInline=true;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=()=>j(Error('Không đọc được video'))});return v}
async function run(record=false){if(!mediaItems.length)throw Error('Hãy thêm ít nhất 1 ảnh hoặc video.');running=true;const c=cfg(),ctx=c.getContext('2d'),t=templates[$('template').value];let rec,chunks=[],audioEl,audioCtx;if(record){if(!window.MediaRecorder||!c.captureStream)throw Error('Safari này chưa hỗ trợ xuất video.');const st=c.captureStream(30);if(musicFile){audioEl=new Audio(obj(musicFile));audioEl.loop=true;audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaElementSource(audioEl),gain=audioCtx.createGain(),dest=audioCtx.createMediaStreamDestination();gain.gain.value=+$('musicVolume').value/100;src.connect(gain);gain.connect(dest);gain.connect(audioCtx.destination);dest.stream.getAudioTracks().forEach(tr=>st.addTrack(tr));await audioCtx.resume();await audioEl.play()}const types=['video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp8,opus','video/webm'];const mime=types.find(MediaRecorder.isTypeSupported)||'';rec=new MediaRecorder(st,mime?{mimeType:mime,videoBitsPerSecond:$('quality').value==='1080'?8000000:4500000}:undefined);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.start(1000)}
try{const base=+$('photoDuration').value,total=mediaItems.length*base+3;let done=0;for(const m of mediaItems){if(!running)break;const src=await source(m);let dur=base;if(m.type==='video'){dur=Math.min(Math.max(src.duration||base,1),12);try{await src.play()}catch{}}const start=performance.now();while(running&&(performance.now()-start)/1000<dur){const p=(performance.now()-start)/1000/dur;ctx.fillStyle='#111';ctx.fillRect(0,0,c.width,c.height);fit(ctx,src,c.width,c.height,m.type==='image'?1+p*.06:1);overlay(ctx,c,t,false);$('exportProgress').value=Math.min(92,(done+p*dur)/total*100);await wait(33)}done+=dur;if(m.type==='video')src.pause()}if(running){const st=performance.now();while(running&&(performance.now()-st)<3000){ctx.fillStyle='#142334';ctx.fillRect(0,0,c.width,c.height);overlay(ctx,c,t,true);$('exportProgress').value=92+(performance.now()-st)/3000*8;await wait(33)}}}finally{if(record&&rec){if(audioEl)audioEl.pause();await new Promise(r=>{rec.onstop=r;rec.stop()});if(audioCtx)await audioCtx.close();const type=rec.mimeType||chunks[0]?.type||'video/webm',blob=new Blob(chunks,{type}),u=URL.createObjectURL(blob);urls.push(u);const a=$('downloadLink');a.href=u;a.download=type.includes('mp4')?'shipping-video.mp4':'shipping-video.webm';a.textContent=type.includes('mp4')?'Lưu video MP4':'Lưu video WebM';a.classList.remove('hidden');$('exportProgress').value=100;setStatus('Tạo video xong. Bấm Lưu video.')}running=false}}
$('previewBtn').onclick=async()=>{try{running=false;await wait(50);setStatus('Đang xem thử…');await run(false);setStatus('Xem thử xong.')}catch(e){running=false;setStatus(e.message)}};$('stopBtn').onclick=()=>running=false;$('exportBtn').onclick=async()=>{try{running=false;await wait(50);setStatus('Đang dựng video. Giữ app mở…');await run(true)}catch(e){running=false;setStatus('Không thể xuất video: '+e.message+' Hãy thử 720p hoặc giảm số cảnh.')}};function setStatus(s){$('status').textContent=s}
load();$('volumeValue').textContent=$('musicVolume').value+'%';renderSuggestions();drawPlaceholder();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));